# docker-compose up to turn on necessary containers (database)
version: '3.7'

services:
  #  app:
  #    image: 'buddies-api:0.0.1-SNAPSHOT'
  #    build:
  #      context: .
  #    container_name: app
  #    depends_on:
  #      - db
  #    ports:
  #      - "8080:8080"
  #    environment:
  #      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
  #      - SPRING_DATASOURCE_USERNAME=compose-postgres
  #      - SPRING_DATASOURCE_PASSWORD=compose-postgres
  #      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:17.2-alpine'
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/dbinit/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=compose-postgres

volumes:
  pgdata: