spring:
  config:
      #    For local environment create a file with variables specified in main application.yaml
    import: template-env.yaml

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: ToBeReplaced
    username: ToBeReplaced
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none