#Development only
spring:
  config:
#    For local environment create a file with variables based on template-env.yaml
    import: dev-env.yaml

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true