CREATE TABLE PUBLIC.LOCATION
(
    LOCATION_ID   NUMERIC(38)      NOT NULL,
    READABLE_TEXT VARCHAR(255)     NOT NULL,
    LONGITUDE     DOUBLE PRECISION NOT NULL,
    LATITUDE      DOUBLE PRECISION NOT NULL,
    CONSTRAINT LOCATION_PK PRIMARY KEY (LOCATION_ID)
);

CREATE TABLE PUBLIC.ACCOUNT
(
    ACCOUNT_ID      NUMERIC(38)  NOT NULL,
    EMAIL           VARCHAR(255) NOT NULL,
    HASHED_PASSWORD VARCHAR(255) NOT NULL,
    NAME            VARCHAR(255) NOT NULL,
    LAST_NAME       VARCHAR(255) NOT NULL,
    LOCATION_ID     NUMERIC(38)  NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION
);

CREATE TABLE PUBLIC.RENTAL
(
    RENTAL_ID     NUMERIC(38)   NOT NULL,
    AUTHOR_ID     NUMERIC(38)   NOT NULL,
    TITLE         VARCHAR(255)  NOT NULL,
    IS_NEGOTIABLE VARCHAR(255)  NOT NULL,
    DESCRIPTION   VARCHAR(3000) NOT NULL,
    LOCATION_ID   NUMERIC(38)   NOT NULL,
    PRICE         NUMERIC(15)   NOT NULL,
    DEPOSIT       NUMERIC(15)   NOT NULL,
    ROOMS         NUMERIC(15)   NOT NULL,
    FLOOR         NUMERIC(15)   NOT NULL,
    SIZE          NUMERIC(5, 2) NOT NULL,
    BUILD_YEAR    NUMERIC(15)   NOT NULL,
    RENT_DATE     TIMESTAMP     NOT NULL,
    CONSTRAINT RENTAL_PK PRIMARY KEY (RENTAL_ID, AUTHOR_ID),
    CONSTRAINT AUTHOR_FK FOREIGN KEY (AUTHOR_ID) REFERENCES ACCOUNT,
    CONSTRAINT LOCATION_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION
);