CREATE TABLE PUBLIC.ACCOUNT
(
    ACCOUNT_ID      NUMERIC(38)  NOT NULL,
    EMAIL           VARCHAR(255) NOT NULL,
    HASHED_PASSWORD VARCHAR(255) NOT NULL,
    NAME            VARCHAR(255) NOT NULL,
    LAST_NAME       VARCHAR(255) NOT NULL,
    CONSTRAINT ACCOUNT_PK PRIMARY KEY (ACCOUNT_ID)
);

CREATE TABLE PUBLIC.RENTAL
(
    RENTAL_ID     NUMERIC(38)      NOT NULL,
    TITLE         VARCHAR(255)     NOT NULL,
    IS_NEGOTIABLE VARCHAR(255)     NOT NULL,
    DESCRIPTION   VARCHAR(3000)    NOT NULL,
    LOCATION_STR  VARCHAR(255)     NOT NULL,
    LOCATION_LNG  DOUBLE PRECISION NOT NULL,
    LOCATION_LAT  DOUBLE PRECISION NOT NULL,
    PRICE         NUMERIC(15)      NOT NULL,
    DEPOSIT       NUMERIC(15)      NOT NULL,
    ROOMS         NUMERIC(15)      NOT NULL,
    FLOOR         NUMERIC(15)      NOT NULL,
    SIZE          NUMERIC(5, 2)    NOT NULL,
    BUILD_YEAR    NUMERIC(15)      NOT NULL,
    RENT_DATE     TIMESTAMP(9)     NOT NULL,
    CONSTRAINT RENTAL_PK PRIMARY KEY (RENTAL_ID)
);